// src/shared/messages.ts の getRendererCopy と同じ文言。bundler が無いので UI 側にも置く。
let uiCopy = {
  helpOpenLabel: 'ヘルプ',
  helpTopics: {},
  invalidPort: 'ポートは 1024〜65535 で指定してください',
  invalidLikeMilestone: 'いいねの区切りは 1 以上の整数にしてください',
  invalidDisplaySec: '表示時間は 1〜120 秒で指定してください',
  invalidDisplayChars: '表示の文字数上限は 10〜400 にしてください',
  invalidSpeechChars: '読み上げの文字数上限は 10〜400 にしてください',
  invalidMaxQueue: '待ちの上限は 1〜100 にしてください',
  invalidHotkeySame: '飛ばす・読み上げ待ち捨て・固定枠待ち捨てのキーは別にしてください',
  invalidPinSec: '固定枠の表示時間は 1〜120 秒で指定してください',
  hotkeyTitle: 'ショートカット',
  hotkeySkipLabel: '読み上げを飛ばすキー',
  hotkeyClearLabel: '読み上げの待ちを捨てるキー',
  hotkeyClearPinLabel: '固定枠の待ちを捨てるキー',
  skipSpeechButton: '読み上げを飛ばす',
  clearSpeechButton: '読み上げの待ちを捨てる',
  clearPinButton: '固定枠の待ちを捨てる',
  hotkeyPress: 'キーを押す',
  hotkeyUnset: '消す',
  hotkeyHint:
    'ボタンを押してから、使いたいキーを押します。Shift や Ctrl も一緒に押せます。消すとキーは効かなくなり、コメント画面のボタンだけ使えます。入力欄にいるときは効きません。',
  voicevoxLaunching: 'VOICEVOXを起動しています…',
  viewerEmpty: '接続するとコメントがここに出ます',
  viewerCleared: 'コメント画面を消しました',
  viewerStatusConnected: '配信に接続しました',
  viewerStatusDisconnected: '切断しました',
  viewerStatusDisconnectedFromLive: '配信から切断しました',
  viewerRoomCount: '同時視聴者数 {count}人',
  viewerRoomTopLabel: '上位ギフト',
  viewerRoomTopCoins: '{coin}ダイヤ',
  viewerPaneComments: 'コメント',
  viewerPaneEvents: 'ギフト・フォローなど',
  viewerEmptyComments: 'まだコメントはありません',
  viewerEmptyEvents: 'ギフトやフォローが来るとここに出ます',
  viewerSplitLabel: 'コメントとイベントの幅',
  viewerLayoutLabel: 'コメント画面のレイアウト',
  viewerLayoutCombined: 'まとめる',
  viewerLayoutSplit: '分ける',
  viewerLayoutCustom: '自由配置',
  viewerLayoutCustomHint:
    '欄の見出しを他の欄の端へドラッグすると分割できます。種類を中央へドロップすると移せます。',
  viewerDisplayLabel: 'コメント画面に出すもの',
  viewerDisplayShort: 'この画面',
  eventDisplayLabel: '配信ソース',
  viewerFontSizeLabel: 'コメント画面の文字サイズ',
  overlayMotionLabel: '動き',
  overlayMotionHint:
    'コメントと固定枠が出るときと消えるときの動きです。次に出る行から効きます。プレビューは選ぶと再生されます。',
  overlayMotionSpeedLabel: '速さ',
  overlayMotionReplay: '動きを見る',
  settingsTabLook: '配信の見た目',
  lookTabHint:
    'ここは視聴者の画面（配信ソース）の見た目です。コメント画面の文字サイズや欄は、コメント画面の上で変えます。',
  lookChatTitle: 'コメント列',
  copyObsLabel: 'OBS用をコピー',
  overlayMotionFuwatto: 'ふわっと',
  overlayMotionFade: 'フェード',
  overlayMotionSlideUp: '下から',
  overlayMotionSlideDown: '上から',
  overlayMotionSlideLeft: '左から',
  overlayMotionSlideRight: '右から',
  overlayMotionZoom: '拡大',
  overlayMotionBounce: 'バウンス',
  overlayMotionBlur: 'ぼかし',
  overlayMotionFlip: '裏返り',
  overlayMotionNone: 'なし',
  overlayMotionSpeed1: 'とても遅い',
  overlayMotionSpeed2: '遅い',
  overlayMotionSpeed3: 'ふつう',
  overlayMotionSpeed4: '速い',
  overlayMotionSpeed5: 'とても速い',
  overlayPinTitle: '固定枠',
  overlayPinHint:
    'ギフトなどはコメント列のすぐ上に1件ずつ出します。来た順です。コメント画面には出ません。',
  overlayPinEnabledLabel: '固定枠を使う',
  overlayPinEnabledHint: 'オフにすると、今までどおり全部下から流れます。',
  overlayPinSecLabel: '固定枠の表示時間（秒）',
  overlayPinHoldLabel: '次が無いときは出したまま',
  overlayPinHoldHint:
    'オンのとき、待ちが無ければ枠を消しません。次が来たら今の秒数のあと切り替わります。',
  overlayPinTypesLabel: '固定枠に出す種類',
  overlayPinTypesHint: 'オフにすると、その種類はコメントと一緒に流れます。初期はコメント以外が全部固定枠です。',
  overlayPinPreviewLabel: 'プレビューも固定枠で見る',
  overlayPinPreviewHint:
    'オフにすると、プレビューだけ今までどおり全部流れます。オンのときは固定枠の種類を表示時間ごとに順に切り替えます。配信ソースは常に上の設定です。',
  viewerUnknownUser: '名前なし',
  viewerBadgeFan: 'メンレベ',
  viewerBadgeSuperFan: 'スパファン',
  viewerBadgeMod: 'モデ',
  viewerBadgeAnchor: '配信者',
  viewerSearchLabel: '検索',
  viewerSearchPlaceholder: '名前・ID・本文',
  viewerSearchEmpty: '一致する行がありません',
  menuView: '窓',
  menuLog: 'サンプル',
  alwaysOnTopMenu: '手前に置く',
  compactMenu: 'コンパクトな窓',
  viewerPreviewSamples: 'コメント画面にサンプル',
  overlayPreviewSamples: '配信ソースにサンプル',
  overlayClearChat: '配信ソースを消す',
  overlayNotConnected:
    '配信ソースに繋がっていません。LIVE Studio用URLを貼り、ソースを更新してください',
  overlayServerDown:
    '配信ソースのサーバーが止まっています。前のコメ読みちゃんを閉じるか、ポート番号を変えてください',
  overlayClientsWaiting:
    '配信ソースのサーバーは起動中です。LIVE StudioにURLを貼ってソースを更新してください',
  overlayClientsConnected: '配信ソース {n}件接続',
  viewerSaveLog: 'ログを保存',
  viewerClearLog: 'コメント画面を消す',
  viewerLogSaved: 'コメントログを保存しました',
  viewerLogEmpty: '保存する行がまだありません',
  viewerLogFailed: 'コメントログの保存に失敗しました',
  viewerFocusOn: '同じ人の行を強調しています。もう一度クリックで解除します',
  speakFanSubOnlyLabel: 'メンレベとスーパーファンのコメントだけ読む',
  speakFanSubOnlyHint:
    'オフのときは全員読みます。オンのときだけ下の条件が効きます。ギフトやフォローはそのままです。',
  speakFanMinLevelLabel: 'メンレベは何以上を読む',
  speakSubscriberCommentsLabel: 'スーパーファンは読む',
  speakSubscriberCommentsHint: 'メンレベ未加入でもスーパーファンなら読みます。',
  fanLevelLookLabel: 'メンレベの色',
  fanLevelLookHint:
    'このレベ以上で印の色が変わります。印はファンクラブ名＋レベ、取れないときはメンレベ＋数字です。',
  skipRepeatSpeechLabel: '同じ人の連投は読み上げない',
  skipRepeatSpeechHint:
    '短い間隔で同じ人が続けてコメントしたとき、表示はして読み上げだけ飛ばします。',
  repeatSpeechSecLabel: '連投とみなす間隔',
  uniqueIdRequired: 'TikTok IDを入力してください',
  lookingUp: 'アカウントを確認しています…',
  alreadyConnected: 'すでに接続しています',
  resetConfigLabel: '設定を初期化する',
  resetConfigHint:
    '文言・見た目・読み上げ・フィルタなどを最初の状態に戻します。TikTok ID と配信画面用のポートは残します。',
  exportConfigLabel: '設定を書き出す',
  importConfigLabel: '設定を読み込む',
  transferConfigHint:
    'ファイルに書き出して、別のPCや再インストール後に戻せます。VOICEVOXの場所は別のPCだと直してください。',
  confirmUserTitle: 'このアカウントに接続しますか？',
  confirmUserHint: '違う人ならやめて、TikTok ID を直してください。',
  confirmUserButton: 'この人で接続',
  confirmUserCancel: 'やめる',
  viewerMuteUser: 'ミュート（読み上げしない）',
  viewerUnmuteUser: 'ミュート解除',
  viewerBlockUser: 'ブロック（表示も読み上げもしない）',
  viewerUnblockUser: 'ブロック解除',
  viewerCopyComment: 'コメントをコピー',
  viewerCopyId: 'IDをコピー',
  viewerCopyNickname: 'ニックネームをコピー',
  viewerUserMissing: 'この行からユーザーを特定できません',
  viewerCommentCopied: 'コメントをコピーしました',
  viewerIdCopied: 'IDをコピーしました',
  viewerNicknameCopied: 'ニックネームをコピーしました',
  viewerCommentCopyFailed: 'コピーできませんでした',
  viewerCommentEmpty: 'コピーする文言がありません',
  viewerIdEmpty: 'IDがありません',
  viewerNicknameEmpty: 'ニックネームがありません',
  viewerUserMuted: '{user} をミュートしました。読み上げしません',
  viewerUserUnmuted: '{user} のミュートを解除しました',
  viewerUserBlocked: '{user} をブロックしました。表示も読み上げもしません',
  viewerUserUnblocked: '{user} のブロックを解除しました',
  guideNeedIdTitle: '最初にやること',
  guideNeedIdExtra: '自分の TikTok ID（先頭の @ は不要）を入れると、接続できます。',
  guideNeedIdButton: '設定で ID を入れる',
  guideNeedConnectTitle: '次は接続です',
  guideNeedConnectExtra:
    '「接続」を押すと、アイコンと名前が出ます。自分か確認してからつなぎます。',
  guideNeedConnectButton: '接続する',
  guideWaitingTitle: '配信の開始を待っています',
  guideWaitingExtra:
    'いつものように TikTok で配信を開始してください。LIVE Studio でもスマホでも大丈夫です。',
  guideLiveTitle: '接続できました',
  guideLiveExtra:
    'コメントが来るとここに出ます。視聴者の画面にも出すときは、配信ソフトに URL を貼ります。',
  guideLiveButton: '配信画面用URLをコピー',
  guideStepId: '設定で TikTok ID を入れる',
  guideStepConnect: '「接続」を押して相手を確認する',
  guideStepLive: 'TikTok で配信を開始する',
  guideSamplesButton: 'サンプルを見る',
  guideClearSamplesButton: 'サンプルを消す',
  viewerTypes: {
    comment: 'コメント',
    gift: 'ギフト',
    follow: 'フォロー',
    share: 'シェア',
    subscribe: 'スパファン',
    superFan: 'スパファン',
    envelope: '宝箱',
    portal: 'ポータル',
    like: 'いいね',
    member: '入室',
  },
};
