// src/shared/messages.ts の getRendererCopy と同じ文言。bundler が無いので UI 側にも置く。
let uiCopy = {
  helpOpenLabel: 'ヘルプ',
  helpTopics: {},
  invalidPort: 'ポートは 1024〜65535 で指定してください',
  invalidLikeMilestone: 'いいねの区切りは 1 以上の整数にしてください',
  invalidOverlayLikeRankingMax: 'ランキングの人数は 1〜10 にしてください',
  invalidOverlayRankingLikePollSec: 'ポーリング間隔は 1〜300 秒にしてください',
  overlayRankingMotionLabel: '入れ替わりの動き',
  overlayRankingMotionHint:
    '順位が変わったときの動きです。スライドは行が上下に移動し、ふわっとは切り替わり、強調は上がった行を光らせます。「サンプルを出す」と入れ替わりを繰り返し、動きや速さを変えるとその場で切り替わります。「表示を消す」で止まります。',
  overlayRankingMotionSlide: 'スライド',
  overlayRankingMotionSoft: 'ふわっと',
  overlayRankingMotionEmphasis: 'スライド＋強調',
  overlayRankingMotionSpeedLabel: '入れ替わりの速さ',
  overlayRankingMotionSpeed1: '遅い',
  overlayRankingMotionSpeed2: 'ふつう',
  overlayRankingMotionSpeed3: '速い',
  invalidDisplaySec: '表示時間は 1〜120 秒で指定してください',
  invalidDisplayChars: '表示の文字数上限は 10〜400 にしてください',
  invalidSpeechChars: '読み上げの文字数上限は 10〜400 にしてください',
  invalidMaxQueue: '待ちの上限は 1〜100 にしてください',
  invalidHotkeySame: '飛ばす・読み上げ待ち捨て・固定枠待ち捨て・一時停止・サウンドミュートのキーは別にしてください',
  invalidPinSec: '固定枠の表示時間は 1〜120 秒で指定してください',
  invalidEventAlertSec: 'イベントアラートの表示時間は 1〜120 秒で指定してください',
  eventAlertLabel: 'イベントアラート',
  eventAlertHint:
    '別の配信ソース（イベントアラート用URL）に出します。初期は種類ごとの同梱GIFです。画像を選ぶと差し替え、× でテンプレに戻せます。',
  eventAlertGiftHint:
    '別の配信ソース（イベントアラート用URL）に出します。初期はもらったギフトの画像です。取れないときは同梱GIFを出します。画像を選ぶと差し替え、× でもらったギフトに戻せます。',
  eventAlertMediaAuto: 'もらったギフト',
  eventAlertMediaTemplate: 'テンプレ',
  eventAlertMediaFile: 'ファイル',
  eventAlertMediaNone: 'なし',
  eventAlertMediaAutoHint:
    '初期はもらったギフトの画像です。取れないときは同梱GIFを出します。画像を選ぶと差し替え、× でもらったギフトに戻せます。',
  eventAlertTemplateNames: {
    gift: 'ギフト用テンプレ',
    follow: 'フォロー用テンプレ',
    share: 'シェア用テンプレ',
    superFan: 'スパファン用テンプレ',
    envelope: '宝箱用テンプレ',
    portal: 'ポータル用テンプレ',
    like: 'いいね用テンプレ',
    member: '入室用テンプレ',
  },
  eventAlertPickMedia: '画像を選ぶ',
  eventAlertResetTemplate: 'テンプレに戻す',
  eventAlertResetAuto: 'もらったギフトに戻す',
  eventAlertSecLabel: '表示時間',
  eventAlertChatUrlTitle: 'コメント列（固定枠あり）',
  eventAlertAlertsUrlTitle: 'イベントアラート',
  eventAlertAlertsUrlHint:
    '中央に画像や GIF を出す用です。ギフトはもらった画像（取れないときは同梱GIF）、他は同梱GIFが初期です。コメント列とは別に、配信ソフトへソースを追加してこの URL を貼ってください。',
  overlayUrlLikesTitle: 'ランキング',
  overlayUrlLikesHint:
    'セッション中のいいね／ダイヤ累計トップを出す用です。コメント列とは別に、配信ソフトへソースを追加してこの URL を貼ってください。',
  overlayLikeRankingEnabledLabel: 'ランキングを配信ソースに出す',
  overlayLikeRankingMaxLabel: 'ランキングの表示人数',
  overlayLikeRankingHint:
    '上の URL を別ソースとして貼ります。配信中の累計トップです（接続し直すとリセット）。見た目は下で変えられます。',
  overlayRankingModeLabel: 'ランキングの種類',
  overlayRankingModeLikes: 'いいね',
  overlayRankingModeDiamonds: 'ダイヤ',
  overlayRankingModeHint:
    'いいねはセッション中のいいね累計、ダイヤは通常ギフトの個数×ダイヤの累計です。',
  overlayRankingLikeSyncLabel: 'いいねの更新',
  overlayRankingLikeSyncLive: '常時',
  overlayRankingLikeSyncPoll: 'ポーリング',
  overlayRankingLikeSyncHint:
    'いいねが多い配信ではポーリングにすると配信ソースの負荷を抑えられます。ダイヤは常に即時です。',
  overlayRankingLikePollSecLabel: 'ポーリング間隔（秒）',
  likesLookTitle: 'ランキングの見た目',
  likesLookHint:
    'ランキング配信ソース専用の見た目です。プリセットを選んでから微調整できます。右のプレビューで確認できます。配信ソースへ出すときは「サンプルを出す」です。',
  lookSectionComment: 'コメント',
  lookSectionRanking: 'ランキング',
  lookSectionAlerts: 'アラート',
  lookSectionEasy: 'かんたん見た目',
  lookSectionChat: 'コメントと固定枠',
  lookSectionName: '名前と色',
  lookSectionsLabel: 'オーバーレイの区分',
  lookCommentSectionsLabel: 'コメントの区分',
  lookAlertsHint:
    '画像・文言・表示秒はイベントタブです。右のプレビューはサンプルを繰り返します。「サンプルを出す」で配信ソースも同じ繰り返しになり、「表示を消す」で配信ソースだけ止まります。',
  likesLookShowAvatarLabel: 'アイコン（アバター）を出す',
  likesLookShowUnitLabel: 'アイコン（ハート／ダイヤ）を付ける',
  likesLookPresetStandard: '標準',
  likesLookPresetLuxury: '豪華',
  likesLookPresetCompact: 'コンパクト',
  likesLookPresetNeon: 'ネオン',
  likesLookPresetMinimal: 'シンプル',
  overlayUrlCardTitle: '配信ソースURL',
  overlayUrlKindLabel: '配信ソースの種類',
  overlayUrlCopyGroupLabel: 'URLのコピー',
  overlayUrlChatHint:
    'TikTok LIVE Studio でソース追加 → リンクに貼るときは LIVE Studio用、OBS のブラウザソースには OBS用を使います。',
  overlayUrlLiveHint:
    '「正しいURLを入力してください」と出るときは、127.0.0.1 を手打ちしていないか確認してください。LIVE Studio用を使います。',
  overlayUrlObsHint:
    'OBS のブラウザソースに貼ってください。自分の耳に二重で聞こえるときは、このソースの音声モニタリングをオフにしてください。',
  overlayUrlAltHint: 'LIVE Studio で上のアドレスが通らないときだけ使います。',
  overlayUrlCopyLiveLabel: 'LIVE Studio用をコピー',
  overlayUrlCopyAltLabel: '別のURLをコピー',
  overlayConnectSampleGroupLabel: '配信ソースの確認',
  overlayConnectSample: 'サンプルを出す',
  overlayConnectClear: '表示を消す',
  overlayConnectSampleHint:
    '今開いている区分の配信ソースにサンプルを出します。ランキングでは入れ替わりを繰り返し、「表示を消す」で止められます。',
  pickAlertMediaTitle: 'アラート用の画像・GIFを選ぶ',
  pickAlertMediaFilter: '画像',
  pickAlertMediaFailed: 'アラート画像の取り込みに失敗しました',
  invalidGiftChimeBandOverlap: 'ダイヤ数の帯が重なっています。範囲を直してください',
  invalidGiftChimeBandRange: 'ダイヤ数の帯は下限≦上限にしてください',
  invalidGiftChimeBandValue: 'ダイヤ数の帯は 0 以上の整数にしてください',
  giftChimeDestinationHint:
    'アプリ本体だけ音が鳴ります（配信ソースには鳴りません）。配信に載せたいときは、OBS などでアプリの音声をキャプチャしてください。',
  giftChimeMatchGift: 'ギフトの種類',
  giftChimeMatchDiamond: 'ダイヤ数',
  giftSpeakSearchLabel: '検索',
  giftSpeakSearchPlaceholder: '名前・ダイヤ',
  giftSpeakSearchEmpty: '一致するギフトがありません',
  giftSpeakEnableAll: '全選択',
  giftSpeakEnableNone: '全外し',
  giftSpeakBulkGroupLabel: '有効の一括操作',
  giftTestHint:
    '空のときは仮のバラになります。配信中に届いたギフトは一覧へ足されて保存されます。',
  giftCatalogReloadHint:
    '普段は押さなくて大丈夫です。最初からよくあるギフトが入っていて、配信中に来た分は自動で足されます。まとめて取り直したいときだけ使ってください。',
  giftCatalogReloadButton: '一覧を再取得',
  giftChimeColEnable: '有効',
  giftChimeColGift: 'ギフト',
  giftChimeColSound: 'サウンド',
  giftChimeColVolume: '音量',
  giftChimeSelectSound: '選択',
  giftChimeVolumeLabel: '音量',
  giftChimeCommonVolumeLabel: '共通の音量',
  giftChimeCommonVolumeHint:
    'テンプレ音（個別音を選んでいないギフト）の音量です。一覧の音量バーは個別ファイル音のときだけ変えられます。',
  giftChimeTestButton: '再生',
  giftChimeStopButton: '停止',
  giftChimeTestFailed: '効果音のテストに失敗しました',
  giftChimeDiamondBandsHint:
    '上限を空にするとそれ以上全部。範囲外は無音。帯の重複は保存できません。',
  giftChimeDiamondMinPlaceholder: '下限',
  giftChimeDiamondMaxPlaceholder: '上限（空可）',
  giftChimeDiamondBandAdd: '帯を追加',
  giftChimeDiamondBandMaxReached: 'ダイヤ数の帯は 30 個までです',
  giftChimeDiamondBandTest: 'テスト送信',
  giftChimeDiamondBandRemove: '削除',
  nicknameAddNeedBoth: 'TikTok ID と呼び方の両方を入れてください',
  listAlreadyExists: 'すでにあります',
  listEmpty: 'まだありません',
  listRemoveLabel: '削除',
  soundResetTemplate: 'テンプレに戻す',
  giftChimeSoundResetHint: '× でテンプレに戻す',
  hotkeyTitle: 'ショートカット',
  hotkeySkipLabel: '読み上げを飛ばすキー',
  hotkeyClearLabel: '読み上げの待ちを捨てるキー',
  hotkeyClearPinLabel: '固定枠の待ちを捨てるキー',
  hotkeyPauseLabel: '読み上げを一時停止するキー',
  hotkeyMuteCommentSoundLabel: 'サウンドをミュートするキー',
  skipSpeechButton: '読み上げを飛ばす',
  clearSpeechButton: '読み上げの待ちを捨てる',
  clearPinButton: '固定枠の待ちを捨てる',
  pauseSpeechButton: '読み上げを一時停止',
  resumeSpeechButton: '読み上げを再開',
  muteCommentSoundButton: 'サウンドをミュート',
  unmuteCommentSoundButton: 'サウンドミュート解除',
  operationsMenu: '操作',
  speechPaused: '読み上げを一時停止しました',
  speechResumed: '読み上げを再開しました',
  commentSoundMuted: 'コメントサウンドを一時ミュートしました',
  commentSoundUnmuted: 'コメントサウンドのミュートを解除しました',
  hotkeyPress: 'キーを押す',
  hotkeyUnset: '消す',
  hotkeyHint:
    'ボタンを押してから、使いたいキーを押します。Shift や Ctrl も一緒に押せます。消すとキーは効かなくなり、コメント画面のボタンだけ使えます。入力欄にいるときは効きません。',
  nicknameRename: '呼び方を変える',
  nicknameClear: '呼び方を消す',
  nicknamePrompt: '読み上げと画面に出す名前',
  profileNeedDisconnect: '配信に接続中はプロファイルを切り替えられません。切断してください',
  profileHint:
    '見た目・読み上げ・フィルタなどを名前付きで保存し、切断中だけ切り替えられます。TikTok ID とポートは変わりません。',
  profileNameLabel: 'プロファイル名',
  profileNamePlaceholder: '例: 配信用',
  profileSelectLabel: '保存済み',
  profileNameRequired: 'プロファイル名を入力してください',
  profileSaveOk: 'プロファイルを保存しました',
  profileSaveButton: '今の設定を保存',
  profileApplyButton: '適用',
  profileDeleteButton: '削除',
  pickSoundFailed: '効果音の取り込みに失敗しました',
  saveOk: '設定を保存しました',
  saveFailed: '保存に失敗しました',
  voicevoxLaunching: 'VOICEVOXを起動しています…',
  viewerEmpty: '接続するとコメントがここに出ます',
  viewerCleared: 'コメント画面を消しました',
  viewerStatusConnected: '配信に接続しました',
  viewerStatusDisconnected: '切断しました',
  viewerStatusDisconnectedFromLive: '配信から切断しました',
  viewerRoomCount: '同時視聴者数 {count}人',
  viewerRoomTopLabel: '上位ギフト',
  viewerRoomTopCoins: '{coin}ダイヤ',
  viewerPaneComments: 'コメント',
  viewerPaneEvents: 'ギフト・フォローなど',
  viewerEmptyComments: 'まだコメントはありません',
  viewerEmptyEvents: 'ギフトやフォローが来るとここに出ます',
  viewerSplitLabel: 'コメントとイベントの幅',
  viewerLayoutLabel: 'コメント画面のレイアウト',
  viewerLayoutCombined: 'まとめる',
  viewerLayoutSplit: '分ける',
  viewerLayoutCustom: '自由配置',
  viewerLayoutCustomHint:
    '欄の見出しを他の欄の端へドラッグすると分割できます。種類を中央へドロップすると移せます。',
  viewerDisplayLabel: 'コメント画面に出すもの',
  viewerDisplayShort: 'この画面',
  eventDisplayLabel: '配信ソースに表示',
  eventSpeakLabel: '音を出す',
  previewZoomLabel: 'プレビューの拡大',
  giftSpeakListHint:
    '初期一覧にないギフトは、配信中に投げられると自動で足されます。鳴らすギフトだけオンにしてください。読み上げモードの TTS には効きません。',
  viewerFontSizeLabel: 'コメント画面の文字サイズ',
  overlayMotionLabel: '動き',
  overlayMotionHint:
    'コメントと固定枠が出るときと消えるときの動きです。次に出る行から効きます。プレビューは選ぶと再生されます。',
  overlayMotionSpeedLabel: '速さ',
  overlayMotionReplay: '動きを見る',
  settingsTabLook: 'オーバーレイ',
  lookTabHint:
    '視聴者の画面に出す配信ソースです。上の区分でコメント・ランキング・アラートを切り替え、右のプレビューで確認します。\n\nコメント画面の文字サイズや欄の幅は、コメント画面上のコントロールで変えます。',
  lookChatTitle: 'コメント列',
  copyObsLabel: 'OBS用をコピー',
  copyFailed: 'コピーに失敗しました',
  copied: 'LIVE Studio用URLをコピーしました。このアドレスを貼ってください',
  overlayMotionFuwatto: 'ふわっと',
  overlayMotionFade: 'フェード',
  overlayMotionSlideUp: '下から',
  overlayMotionSlideDown: '上から',
  overlayMotionSlideLeft: '左から',
  overlayMotionSlideRight: '右から',
  overlayMotionZoom: '拡大',
  overlayMotionBounce: 'バウンス',
  overlayMotionBlur: 'ぼかし',
  overlayMotionFlip: '裏返り',
  overlayMotionNone: 'なし',
  overlayMotionSpeed1: 'とても遅い',
  overlayMotionSpeed2: '遅い',
  overlayMotionSpeed3: 'ふつう',
  overlayMotionSpeed4: '速い',
  overlayMotionSpeed5: 'とても速い',
  overlayPinTitle: '固定枠',
  overlayPinHint:
    'ギフトなどはコメント列のすぐ上に1件ずつ出します。来た順です。表示時間は入場から退場が終わるまでです。コメント画面には出ません。',
  overlayPinEnabledLabel: '固定枠を使う',
  overlayPinEnabledHint: 'オフにすると、今までどおり全部下から流れます。',
  overlayPinSecLabel: '固定枠の表示時間（秒）',
  overlayPinHoldLabel: '次が無いときは出したまま',
  overlayPinHoldHint:
    'オンのとき、待ちが無ければ枠を消しません。次が来たら表示時間のあと切り替わります。',
  overlayPinTypesLabel: '固定枠に出す種類',
  overlayPinTypesHint:
    'オフにすると、その種類はコメントと一緒に流れます。初期はコメント以外が全部固定枠です。',
  overlayPinPreviewLabel: 'プレビューも固定枠で見る',
  overlayPinPreviewHint:
    'オフにすると、プレビューだけ今までどおり全部流れます。オンのときは固定枠の種類を表示時間ごとに順に切り替えます。プレビューでは音は鳴りません。配信ソースは常に上の設定です。',
  overlayPinTypeSecPlaceholder: '共通',
  overlayPinTypeSecHint: '秒（空=共通）',
  overlayNameColorTitle: '名前の色',
  overlayNameColorEnabledLabel: '配信ソースで名前に色をつける',
  overlayNameColorEnabledHint:
    '同じユーザーは常に同じ色になります。固定枠やイベントアラートにも付きます。初期のパレットのまま（またはかんたん見た目用の色のまま）なら、かんたん見た目のプリセットに合わせた色へ自動で変わります。自分で変えた色はそのままです。差し込み色も同じルールです。',
  overlayNameColorPaletteLabel: '色のパレット（5色）',
  overlayCustomCssSummary: 'カスタム CSS（上級者向け）',
  overlayCustomCssLabel: '上書き用 CSS（空ならかんたん設定のまま）',
  overlayCustomCssHint:
    'コメント列の配信ソースだけに効きます。イベントアラート・ランキングには入りません。かんたん見た目のあとに上書きされます。',
  overlayCustomCssRef: `骨格
.overlay-root
  ol#pin.chat.chat--pin          …固定枠
  ol#chat.chat                   …コメント列
    li.chat__item.chat__item--{種類}
      img.chat__avatar
      img.chat__gift             …ギフト時
      .chat__body
        .chat__name-line
          .chat__name
        .chat__text-line
          .chat__text / .chat__accent / .chat__emote

種類: comment gift follow share superFan envelope portal like member
修飾: .chat--pin .chat--theme-* .chat--align-* .chat--hide-avatar .is-leaving

.chat の変数（例）
--bubble-rgb --bubble-text --bubble-alpha
--body-size --avatar-size --gift-size --item-radius --chat-font
--gift-color --event-color --like-color

例
.chat__item { background: rgb(0 0 0 / 55%); }
.chat__body { font-size: 22px; }
.chat--pin .chat__item { box-shadow: inset 0 0 0 2px #f59f00; }`,
  templateEditorHint:
    '欄の上のボタンで差し込みを入れられます。表示欄では差し込み横の色で強調色を変えられます。色付きの差し込みと **太字** で囲んだ文字は、固定枠・コメント列・イベントアラートで同じ色・太字になります。それ以外の平文は吹き出しの文字色です。{user} だけはユーザーごとの名前色です。差し込み色が初期（またはかんたん見た目用）のままなら、かんたん見た目のプリセットに合わせて変わります。自分で変えた色はそのままです。読み上げでは ** を外して中身だけ読みます。',
  templateEmphasisInsertLabel: '**強調** を挿入',
  templateAccentColorLabel: '差し込みの色',
  colorPickerResetLabel: '初期色に戻す',
  viewerUnknownUser: '名前なし',
  viewerBadgeFan: 'メンレベ',
  viewerBadgeSuperFan: 'スパファン',
  viewerBadgeMod: 'モデ',
  viewerBadgeAnchor: '配信者',
  viewerSearchLabel: '検索',
  viewerSearchPlaceholder: '名前・ID・本文',
  viewerSearchEmpty: '一致する行がありません',
  menuView: '窓',
  menuLog: 'サンプル',
  alwaysOnTopMenu: '手前に置く',
  compactMenu: 'コンパクトな窓',
  minimizeWindow: '最小化',
  maximizeWindow: '最大化',
  restoreWindow: '元のサイズに戻す',
  closeWindow: '閉じる',
  viewerPreviewSamples: 'コメント画面にサンプル',
  overlayPreviewSamples: '配信ソースにサンプル',
  overlayClearChat: '配信ソースを消す',
  overlayNotConnected:
    '配信ソースに繋がっていません。LIVE Studio用URLを貼り、ソースを更新してください',
  overlayServerDown:
    '配信ソースのサーバーが止まっています。前のコメ読みちゃんを閉じるか、ポート番号を変えてください',
  overlayClientsWaiting:
    '配信ソースのサーバーは起動中です。LIVE StudioにURLを貼ってソースを更新してください',
  overlayClientsConnected: '配信ソース {n}件接続',
  viewerSaveLog: 'ログを保存',
  viewerClearLog: 'ログを消す',
  viewerLogSaved: 'コメントログを保存しました',
  viewerLogEmpty: '保存する行がまだありません',
  viewerLogFailed: 'コメントログの保存に失敗しました',
  viewerLogClearTitle: 'コメントログを消しますか？',
  viewerLogClearConfirmOk: '消す',
  viewerLogClearOk: 'コメントログを消しました',
  viewerPaneClearTitle: 'この窓の行を消しますか？',
  viewerPaneClearLabel: 'この窓を消す',
  viewerLogRestoreFailed: 'コメントログの復元に失敗しました',
  viewerLogMaxRowsLabel: 'コメント画面の最大行数',
  viewerLogMaxRowsHint:
    '接続中に追加されたログの保持件数です（全パネル合計）。起動時に前回のログを復元します。設定を減らしても今の行はすぐ消えません。',
  speechReplaceTitle: '読み替え辞書',
  speechReplaceHint:
    'コメント本文の読み上げだけ置き換えます。ギフト名やフォローなどは変わりません。ユーザー名の変更は「呼び方」を使ってください。',
  speechReplaceFormatHint:
    '1行が「変換前」と「変換後」です。区切りはタブまたはカンマ（スペースは区切りにしません）。例: w[タブ]わら または w,わら',
  speechReplaceFormatExample: '例: w[タブ]わら または w,わら',
  speechReplaceCounter: (n, max) => `${n}/${max}件`,
  speechReplaceOverLimit: `辞書の上限（2000件）に達しました。追加と読み込みはできません`,
  speechReplaceExportTitle: '読み替え辞書を書き出す',
  speechReplaceExportFilter: 'テキスト',
  speechReplaceExportOk: '読み替え辞書を書き出しました',
  speechReplaceExportFailed: '書き出しに失敗しました',
  speechReplaceImportTitle: '読み替え辞書を読み込む',
  speechReplaceImportFilter: 'テキスト',
  speechReplaceImportConfirmTitle: '読み替え辞書を読み込みますか？',
  speechReplaceImportConfirm: '今の辞書を上書きします。',
  speechReplaceImportOk: '読み替え辞書を読み込みました',
  speechReplaceImportFailed: '読み込みに失敗しました',
  speechReplaceImportSkipped: (lines) => `不正な形式のため読み飛ばした行: ${lines}`,
  speechReplaceImportOverLimit: `上限（2000件）を超えているため読み込めませんでした`,
  speechReplaceClearAllTitle: '読み替え辞書を全部消しますか？',
  speechReplaceClearAllOk: '全部消す',
  nicknameMapHint:
    'コメント画面と読み上げの表示名を差し替えます（読み替え辞書とは別）。右クリックからも変えられます。次回起動後も残ります。',
  viewerFocusOn: '同じ人の行を強調しています。もう一度クリックで解除します',
  speakFanSubOnlyLabel: '条件を満たすコメントだけ読む',
  speakFanSubOnlyHint:
    'オフのときは全員読みます。オンのときだけ下の条件が効きます。ギフトやフォローはそのままです。',
  speakFanMinLevelLabel: 'メンレベは何以上を読む',
  speakFanClubCommentsLabel: 'メンレベも読む',
  speakFanClubCommentsHint: 'オフにするとメンレベは読まず、スーパーファン条件だけ使えます。',
  speakSubscriberCommentsLabel: 'スーパーファンは読む',
  speakSubscriberCommentsHint: 'メンレベ未加入でもスーパーファンなら読みます。',
  invalidSpeakFanSubEmpty:
    '「条件を満たすコメントだけ読む」をオンにするときは、メンレベかスーパーファンのどちらかをオンにしてください',
  fanLevelLookLabel: 'メンレベの色',
  fanLevelLookHint:
    'このレベ以上でバッジの色が変わります。バッジはファンクラブ名＋レベ、取れないときはメンレベ＋数字です。',
  commentBadgeTitle: 'バッジ',
  commentSoundHint: '読み上げの代わりにアプリ本体で鳴らします（配信ソースには鳴りません）。',
  commentNotifyModeLabel: 'コメントの出し方',
  commentNotifySpeak: '読み上げ',
  commentNotifySound: 'サウンド',
  eventNotifySpeak: '読み上げ',
  eventNotifySound: 'サウンド',
  eventSoundHint: '読み上げの代わりにアプリ本体で鳴らします（配信ソースには鳴りません）。',
  skipRepeatSpeechLabel: '同じ人の連投は読み上げない',
  skipRepeatSpeechHint:
    '短い間隔で同じ人が続けてコメントしたとき、表示はして読み上げだけ飛ばします。',
  repeatSpeechSecLabel: '連投とみなす間隔',
  uniqueIdRequired: 'TikTok IDを入力してください',
  lookingUp: 'アカウントを確認しています…',
  alreadyConnected: 'すでに接続しています',
  resetConfigLabel: '設定を初期化する',
  resetConfigHint:
    '文言・見た目・読み上げ・フィルタなどを最初の状態に戻します。TikTok ID と配信画面用のポートは残します。',
  resetTabLabel: 'このタブを初期化する',
  resetTabHints: {
    connect: 'TikTok ID と、起動時の自動接続を最初の状態に戻します。',
    filter: 'NGワード、ブロック、ミュート、呼び方、読み替えを空に戻します。',
    comment: 'コメントの表示・読み上げ・サウンド・メンレベの色を最初の状態に戻します。',
    gift: 'ギフトの表示・読み上げ・サウンド・アラートを最初の状態に戻します。',
    events: 'フォローから入室までの表示・読み上げ・サウンド・アラートを最初の状態に戻します。',
    look: '配信ソースの見た目と動きを最初の状態に戻します。ポートは残します。',
    tts: '読み上げエンジンと速度などを最初の状態に戻します。',
    app: '手前表示、明るさ、ショートカット、ログの最大行数を最初の状態に戻します。プロファイルは残します。',
  },
  exportConfigLabel: 'プロファイルを書き出す',
  importConfigLabel: 'プロファイルを読み込む',
  transferConfigHint:
    'プロファイルをファイルに書き出して戻せます。TikTok ID とポートは含みません。以前の「設定書き出し」ファイルも読み込めます（ID・ポートは今のまま残ります）。VOICEVOXの場所は別のPCだと直してください。',
  confirmUserTitle: 'このアカウントに接続しますか？',
  confirmUserHint: '違う人ならやめて、TikTok ID を直してください。',
  confirmUserButton: 'この人で接続',
  confirmUserCancel: 'やめる',
  viewerMuteUser: 'ミュート（読み上げしない）',
  viewerUnmuteUser: 'ミュート解除',
  viewerBlockUser: 'ブロック（表示も読み上げもしない）',
  viewerUnblockUser: 'ブロック解除',
  viewerCopyComment: 'コメントをコピー',
  viewerCopyId: 'IDをコピー',
  viewerCopyNickname: 'ニックネームをコピー',
  viewerUserMissing: 'この行からユーザーを特定できません',
  viewerCommentCopied: 'コメントをコピーしました',
  viewerIdCopied: 'IDをコピーしました',
  viewerNicknameCopied: 'ニックネームをコピーしました',
  viewerCommentCopyFailed: 'コピーできませんでした',
  viewerCommentEmpty: 'コピーする文言がありません',
  viewerIdEmpty: 'IDがありません',
  viewerNicknameEmpty: 'ニックネームがありません',
  viewerUserMuted: '{user} をミュートしました。読み上げしません',
  viewerUserUnmuted: '{user} のミュートを解除しました',
  viewerUserBlocked: '{user} をブロックしました。表示も読み上げもしません',
  viewerUserUnblocked: '{user} のブロックを解除しました',
  guideNeedIdTitle: '最初にやること',
  guideNeedIdExtra: '自分の TikTok ID（先頭の @ は不要）を入れると、接続できます。',
  guideNeedIdButton: '設定で ID を入れる',
  guideNeedConnectTitle: '次は接続です',
  guideNeedConnectExtra:
    '「接続」を押すと、アイコンと名前が出ます。自分か確認してからつなぎます。',
  guideNeedConnectButton: '接続する',
  guideWaitingTitle: '配信の開始を待っています',
  guideWaitingExtra:
    'いつものように TikTok で配信を開始してください。LIVE Studio でもスマホでも大丈夫です。',
  guideLiveTitle: '接続できました',
  guideLiveExtra:
    'コメントが来るとここに出ます。視聴者の画面にも出すときは、配信ソフトに URL を貼ります。',
  guideLiveButton: '配信画面用URLをコピー',
  guideStepId: '設定で TikTok ID を入れる',
  guideStepConnect: '「接続」を押して相手を確認する',
  guideStepLive: 'TikTok で配信を開始する',
  guideSamplesButton: 'サンプルを見る',
  guideClearSamplesButton: 'サンプルを消す',
  viewerTypes: {
    comment: 'コメント',
    gift: 'ギフト',
    follow: 'フォロー',
    share: 'シェア',
    subscribe: 'スパファン',
    superFan: 'スパファン',
    envelope: '宝箱',
    portal: 'ポータル',
    like: 'いいね',
    member: '入室',
  },
};
