export const IpcChannels = {
  GET_CONFIG: 'config:get',
  SAVE_CONFIG: 'config:save',
  RESET_CONFIG: 'config:reset',
  EXPORT_CONFIG: 'config:export',
  IMPORT_CONFIG: 'config:import',
  CONFIG_CHANGED: 'config:changed',
  GET_STATUS: 'live:status',
  STATUS_CHANGED: 'live:status-changed',
  CONNECT: 'live:connect',
  DISCONNECT: 'live:disconnect',
  LOOKUP_USER: 'live:lookup-user',
  GET_TTS_VOICES: 'tts:voices',
  CHECK_TTS_ENGINE: 'tts:check',
  PREVIEW_TTS: 'tts:preview',
  SKIP_SPEECH: 'tts:skip',
  CLEAR_SPEECH_QUEUE: 'tts:clear-queue',
  COPY_VOICEVOX_CREDIT: 'tts:copy-credit',
  PICK_VOICEVOX_EXE: 'tts:pick-voicevox',
  LAUNCH_VOICEVOX: 'tts:launch-voicevox',
  APP_NOTICE: 'app:notice',
  VIEWER_EVENT: 'viewer:event',
  SAVE_SESSION_LOG: 'log:save',
  SEND_TEST_EVENT: 'tester:send',
  GET_TEST_GIFTS: 'tester:gifts',
  REFRESH_TEST_GIFTS: 'tester:gifts-refresh',
  PREVIEW_OVERLAY: 'overlay:preview',
  CLEAR_OVERLAY: 'overlay:clear',
  CLEAR_OVERLAY_PIN: 'overlay:clear-pin',
  COPY_OVERLAY_URL: 'overlay:copy-url',
  GET_APP_INFO: 'app:info',
  GET_HELP_CONTENT: 'help:content',
  OPEN_HELP: 'help:open',
  OPEN_EXTERNAL: 'app:open-external',
  WINDOW_FIT_CONTENT: 'window:fit-content',
  WINDOW_CLOSE: 'window:close',
} as const;

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels];
